ci: remove unnecessary docker login (#822)
Causing:

```
Error: Cannot perform an interactive login from a non TTY device
Error: Process completed with exit code 1.
```